### PR TITLE
replaced os.system() by subprocess.call(), added oauth2 support

### PR DESCRIPTION
**Pull request by stv0g**

### CODE REVIEW

**Comment by ansell** [comment]
With one minor typo fix, changing "repo.repo" to "repo" on line 86, this works for me, where the previous script that calls out to command line "git" directly does not.

**Comment by stv0g** [comment]
Do you want me to fix that typo?

**Comment by ansell** [comment]
Yes that would be awesome, it is triggered by using -S, which is necessary to backup private repositories.

**Comment by clockfort** [comment]
Looks awesome, sorry for being a horrible, unresponsive maintainer.

If you fix up the merge conflict and the referenced typo, I'll merge. Thanks for this!

**Comment by jvrplmlmn** [comment]
@clockfort any chance that we could get this merged?

**Comment by stv0g** [comment]
Closing in favour of #30

**Pull request closed without merging**
